# A list of available rules and their signatures can be found here: https://buck2.build/docs/api/rules/

prebuilt_cxx_library(
    name = "libpython",
    header_only = True,
    exported_preprocessor_flags = ["-I/usr/include/python3.10", "-v", "-std=c++17"],
    exported_linker_flags = ["-lpython3.10"],
    visibility = ["PUBLIC"]
)
