load("@//defs.bzl", "static_linked_python_binary")

python_binary(
    name="hello",
    main="hello.py",
    main_function="examples.hello_extension.hello.main",
    deps=[":extension"],
)

static_linked_python_binary(
    name="static_linked_hello",
    main="hello.py",
    main_function="examples.hello_extension.hello.main",
    deps=[":extension"],
)

cxx_python_extension(
    name="extension",
    srcs=["extension.cpp"],
    deps=["root//:libpython"],
)
