prebuilt_cxx_library(
    name="libpython",
    header_only=True,
    exported_preprocessor_flags=["-I/usr/include/python3.10", "-std=c++17"],
    exported_linker_flags=["-lpython3.10"],
    visibility=["PUBLIC"],
)
